version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "01:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
