name: release

on:
  push:
    tags:
      - 'v*'        # e.g. v1.3.0 → also updates the "latest" tag

permissions:
  contents: write
  packages: read

env:
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary
        shell: bash
        run: |
          GOOS=$(echo "${{ matrix.os }}" | sed 's/-latest//')
          GOARCH=${{ matrix.arch }}
          EXT=""
          [[ $GOOS == "windows" ]] && EXT=".exe"
          go build -ldflags "-s -w" -o stackfetch-${GOOS}-${GOARCH}${EXT} ./cmd/stackfetch

      - name: Upload (version)
        uses: softprops/action-gh-release@v1
        with:
          files: stackfetch-*
          generate_release_notes: true

      # NOTE: Keep an always‑fresh "latest" release in sync
      - name: Upload (latest alias)
        if: github.repository == vars.REPO
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest
          body: "Mirror of ${{ github.ref_name }}"
          overwrite: true             # just to replace existing assets if they clash
          files: stackfetch-*
