name: release

on:
  push:
    tags:
      - 'v*'

env:
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        shell: bash
        run: |
          GOOS=$(echo "${{ matrix.os }}" | sed -e 's/-latest//')
          GOARCH=${{ matrix.arch }}
          EXT=""
          [[ $GOOS == "windows" ]] && EXT=".exe"
          go build -ldflags "-s -w" -o stackfetch-${GOOS}-${GOARCH}${EXT} ./cmd/stackfetch

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: stackfetch-*
